package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.91

import (
	"context"
	"fmt"
	graphql1 "maritime-test-lab/gen/graphql"
	"maritime-test-lab/gen/graphql/model"
	voyagev1 "maritime-test-lab/gen/proto/voyage/v1"

	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/status"
)

// CreateVoyage is the resolver for the createVoyage field.
func (r *mutationResolver) CreateVoyage(ctx context.Context, input model.CreateVoyageInput) (*model.CreateVoyagePayload, error) {
	if input.ClientRequestID == "" {
		return nil, fmt.Errorf("clientRequestId is required")
	}
	resp, err := r.VoyageClient.CreateVoyage(ctx, &voyagev1.CreateVoyageRequest{
		ClientRequestId: input.ClientRequestID,
		Origin:          input.Origin,
		Dest:            input.Dest,
		DistanceNm:      int32(input.DistanceNm),
		FeesMinor:       int64(input.FeesMinor),
	})
	if err != nil {
		return nil, fmt.Errorf("create voyage: %w", err)
	}
	return &model.CreateVoyagePayload{
		Voyage:                   toModelVoyage(resp.GetVoyage()),
		ProvisionalEstimateMinor: int(resp.GetProvisionalEstimateMinor()),
		EstimatePending:          resp.GetEstimatePending(),
	}, nil
}

// UpdateVoyage is the resolver for the updateVoyage field.
func (r *mutationResolver) UpdateVoyage(ctx context.Context, input model.UpdateVoyageInput) (*model.Voyage, error) {
	resp, err := r.VoyageClient.UpdateVoyage(ctx, &voyagev1.UpdateVoyageRequest{
		Voyage: &voyagev1.Voyage{
			ClientRequestId: input.ClientRequestID,
			Origin:          input.Origin,
			Dest:            input.Dest,
			DistanceNm:      int32(input.DistanceNm),
			FeesMinor:       int64(input.FeesMinor),
			Version:         int64(input.Version),
		},
	})
	if err != nil {
		return nil, fmt.Errorf("update voyage: %w", err)
	}
	return toModelVoyage(resp.GetVoyage()), nil
}

// Voyage is the resolver for the voyage field.
func (r *queryResolver) Voyage(ctx context.Context, clientRequestID string) (*model.Voyage, error) {
	resp, err := r.VoyageClient.GetVoyage(ctx, &voyagev1.GetVoyageRequest{ClientRequestId: clientRequestID})
	if err != nil {
		if status.Code(err) == codes.NotFound {
			return nil, nil // GraphQL null for an unknown voyage
		}
		return nil, fmt.Errorf("get voyage: %w", err)
	}
	return toModelVoyage(resp.GetVoyage()), nil
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
