// Code generated by MockGen. DO NOT EDIT.
// Source: maritime-test-lab/gen/proto/estimator/v1 (interfaces: EstimatorServiceClient)
//
// Generated by this command:
//
//	mockgen -destination services/voyage/adapters/estimatorclient/mock_estimatorservice_test.go -package estimatorclient maritime-test-lab/gen/proto/estimator/v1 EstimatorServiceClient
//

// Package estimatorclient is a generated GoMock package.
package estimatorclient

import (
	context "context"
	estimatorv1 "maritime-test-lab/gen/proto/estimator/v1"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockEstimatorServiceClient is a mock of EstimatorServiceClient interface.
type MockEstimatorServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockEstimatorServiceClientMockRecorder
	isgomock struct{}
}

// MockEstimatorServiceClientMockRecorder is the mock recorder for MockEstimatorServiceClient.
type MockEstimatorServiceClientMockRecorder struct {
	mock *MockEstimatorServiceClient
}

// NewMockEstimatorServiceClient creates a new mock instance.
func NewMockEstimatorServiceClient(ctrl *gomock.Controller) *MockEstimatorServiceClient {
	mock := &MockEstimatorServiceClient{ctrl: ctrl}
	mock.recorder = &MockEstimatorServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEstimatorServiceClient) EXPECT() *MockEstimatorServiceClientMockRecorder {
	return m.recorder
}

// Estimate mocks base method.
func (m *MockEstimatorServiceClient) Estimate(ctx context.Context, in *estimatorv1.EstimateRequest, opts ...grpc.CallOption) (*estimatorv1.EstimateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Estimate", varargs...)
	ret0, _ := ret[0].(*estimatorv1.EstimateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Estimate indicates an expected call of Estimate.
func (mr *MockEstimatorServiceClientMockRecorder) Estimate(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Estimate", reflect.TypeOf((*MockEstimatorServiceClient)(nil).Estimate), varargs...)
}
